export const teamChampionships = {
  lakers: { titles: 17, lastTitle: 2020 },
  celtics: { titles: 18, lastTitle: 2024 },
  bulls: { titles: 6, lastTitle: 1998 },
  warriors: { titles: 7, lastTitle: 2022 },
  cavaliers: { titles: 1, lastTitle: 2016 },
  spurs: { titles: 5, lastTitle: 2014 },
  heat: { titles: 3, lastTitle: 2013 },
  mavericks: { titles: 1, lastTitle: 2011 },
  suns: { titles: 0, lastTitle: null },
  knicks: { titles: 2, lastTitle: 1973 },
  nuggets: { titles: 1, lastTitle: 2023 },
  bucks: { titles: 2, lastTitle: 2021 },
  rockets: { titles: 2, lastTitle: 1995 },
  "76ers": { titles: 3, lastTitle: 1983 },
  pistons: { titles: 3, lastTitle: 2004 },
  raptors: { titles: 1, lastTitle: 2019 },
  nets: { titles: 0, lastTitle: null },
  clippers: { titles: 0, lastTitle: null },
  jazz: { titles: 0, lastTitle: null },
  hawks: { titles: 1, lastTitle: 1958 },
  magic: { titles: 0, lastTitle: null },
  kings: { titles: 1, lastTitle: 1951 },
  blazers: { titles: 1, lastTitle: 1977 },
  grizzlies: { titles: 0, lastTitle: null },
  pelicans: { titles: 0, lastTitle: null },
  timberwolves: { titles: 0, lastTitle: null },
  hornets: { titles: 0, lastTitle: null },
  thunder: { titles: 1, lastTitle: 1979 }, // como Seattle Supersonics
  wizards: { titles: 1, lastTitle: 1978 }, // como Washington Bullets
  pacers: { titles: 0, lastTitle: null },
};

export const champions = {
  1947: {
    team: "Philadelphia Warriors",
    defeated: "Chicago Stags",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Warriors 83, Stags 80",
  },
  1948: {
    team: "Baltimore Bullets",
    defeated: "Philadelphia Warriors",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Bullets 88, Warriors 73",
  },
  1949: {
    team: "Minneapolis Lakers",
    defeated: "Washington Capitols",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Lakers 77, Capitols 56",
  },
  1950: {
    team: "Minneapolis Lakers",
    defeated: "Syracuse Nationals",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Lakers 110, Nationals 95",
  },
  1951: {
    team: "Rochester Royals",
    defeated: "New York Knicks",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Royals 79, Knicks 75",
  },
  1952: {
    team: "Minneapolis Lakers",
    defeated: "New York Knicks",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Lakers 82, Knicks 65",
  },
  1953: {
    team: "Minneapolis Lakers",
    defeated: "New York Knicks",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Lakers 91, Knicks 84",
  },
  1954: {
    team: "Minneapolis Lakers",
    defeated: "Syracuse Nationals",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Lakers 87, Nationals 80",
  },
  1955: {
    team: "Syracuse Nationals",
    defeated: "Fort Wayne Pistons",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Nationals 92, Pistons 91",
  },
  1956: {
    team: "Philadelphia Warriors",
    defeated: "Fort Wayne Pistons",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Warriors 99, Pistons 88",
  },
  1957: {
    team: "Boston Celtics",
    defeated: "St. Louis Hawks",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Celtics 125, Hawks 123 (2OT)",
  },
  1958: {
    team: "St. Louis Hawks",
    defeated: "Boston Celtics",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Hawks 110, Celtics 109",
  },
  1959: {
    team: "Boston Celtics",
    defeated: "Minneapolis Lakers",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: Celtics 118, Lakers 113",
  },
  1960: {
    team: "Boston Celtics",
    defeated: "St. Louis Hawks",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Celtics 122, Hawks 103",
  },
  1961: {
    team: "Boston Celtics",
    defeated: "St. Louis Hawks",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Celtics 121, Hawks 112",
  },
  1962: {
    team: "Boston Celtics",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Celtics 110, Lakers 107 (OT)",
  },
  1963: {
    team: "Boston Celtics",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Celtics 112, Lakers 109",
  },
  1964: {
    team: "Boston Celtics",
    defeated: "San Francisco Warriors",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Celtics 105, Warriors 99",
  },
  1965: {
    team: "Boston Celtics",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Celtics 129, Lakers 96",
  },
  1966: {
    team: "Boston Celtics",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Celtics 95, Lakers 93",
  },
  1967: {
    team: "Philadelphia 76ers",
    defeated: "San Francisco Warriors",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: 76ers 125, Warriors 122",
  },
  1968: {
    team: "Boston Celtics",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Celtics 124, Lakers 109",
  },
  1969: {
    team: "Boston Celtics",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Celtics 108, Lakers 106",
  },
  1970: {
    team: "New York Knicks",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Knicks 113, Lakers 99",
  },
  1971: {
    team: "Milwaukee Bucks",
    defeated: "Baltimore Bullets",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: Bucks 118, Bullets 106",
  },
  1972: {
    team: "Los Angeles Lakers",
    defeated: "New York Knicks",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Lakers 114, Knicks 100",
  },
  1973: {
    team: "New York Knicks",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Knicks 102, Lakers 93",
  },
  1974: {
    team: "Boston Celtics",
    defeated: "Milwaukee Bucks",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Celtics 102, Bucks 87",
  },
  1975: {
    team: "Golden State Warriors",
    defeated: "Washington Bullets",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: Warriors 96, Bullets 95",
  },
  1976: {
    team: "Boston Celtics",
    defeated: "Phoenix Suns",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Celtics 87, Suns 80",
  },
  1977: {
    team: "Portland Trail Blazers",
    defeated: "Philadelphia 76ers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Trail Blazers 109, 76ers 107",
  },
  1978: {
    team: "Washington Bullets",
    defeated: "Seattle SuperSonics",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Bullets 105, SuperSonics 99",
  },
  1979: {
    team: "Seattle SuperSonics",
    defeated: "Washington Bullets",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: SuperSonics 97, Bullets 93",
  },
  1980: {
    team: "Los Angeles Lakers",
    defeated: "Philadelphia 76ers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Lakers 123, 76ers 107",
  },
  1981: {
    team: "Boston Celtics",
    defeated: "Houston Rockets",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Celtics 102, Rockets 91",
  },
  1982: {
    team: "Los Angeles Lakers",
    defeated: "Philadelphia 76ers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Lakers 114, 76ers 104",
  },
  1983: {
    team: "Philadelphia 76ers",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: 76ers 115, Lakers 108",
  },
  1984: {
    team: "Boston Celtics",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Celtics 111, Lakers 102",
  },
  1985: {
    team: "Los Angeles Lakers",
    defeated: "Boston Celtics",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Lakers 111, Celtics 100",
  },
  1986: {
    team: "Boston Celtics",
    defeated: "Houston Rockets",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Celtics 114, Rockets 97",
  },
  1987: {
    team: "Los Angeles Lakers",
    defeated: "Boston Celtics",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Lakers 106, Celtics 93",
  },
  1988: {
    team: "Los Angeles Lakers",
    defeated: "Detroit Pistons",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Lakers 108, Pistons 105",
  },
  1989: {
    team: "Detroit Pistons",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: Pistons 105, Lakers 97",
  },
  1990: {
    team: "Detroit Pistons",
    defeated: "Portland Trail Blazers",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Pistons 92, Blazers 90",
  },
  1991: {
    team: "Chicago Bulls",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Bulls 108, Lakers 101",
  },
  1992: {
    team: "Chicago Bulls",
    defeated: "Portland Trail Blazers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Bulls 97, Blazers 93",
  },
  1993: {
    team: "Chicago Bulls",
    defeated: "Phoenix Suns",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Bulls 99, Suns 98",
  },
  1994: {
    team: "Houston Rockets",
    defeated: "New York Knicks",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Rockets 90, Knicks 84",
  },
  1995: {
    team: "Houston Rockets",
    defeated: "Orlando Magic",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: Rockets 113, Magic 101",
  },
  1996: {
    team: "Chicago Bulls",
    defeated: "Seattle SuperSonics",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Bulls 87, SuperSonics 75",
  },
  1997: {
    team: "Chicago Bulls",
    defeated: "Utah Jazz",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Bulls 90, Jazz 86",
  },
  1998: {
    team: "Chicago Bulls",
    defeated: "Utah Jazz",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Bulls 87, Jazz 86",
  },
  1999: {
    team: "San Antonio Spurs",
    defeated: "New York Knicks",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Spurs 78, Knicks 77",
  },
  2000: {
    team: "Los Angeles Lakers",
    defeated: "Indiana Pacers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Lakers 116, Pacers 111",
  },
  2001: {
    team: "Los Angeles Lakers",
    defeated: "Philadelphia 76ers",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Lakers 108, 76ers 96",
  },
  2002: {
    team: "Los Angeles Lakers",
    defeated: "New Jersey Nets",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: Lakers 113, Nets 107",
  },
  2003: {
    team: "San Antonio Spurs",
    defeated: "New Jersey Nets",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Spurs 88, Nets 77",
  },
  2004: {
    team: "Detroit Pistons",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Pistons 100, Lakers 87",
  },
  2005: {
    team: "San Antonio Spurs",
    defeated: "Detroit Pistons",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Spurs 81, Pistons 74",
  },
  2006: {
    team: "Miami Heat",
    defeated: "Dallas Mavericks",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Heat 95, Mavericks 92",
  },
  2007: {
    team: "San Antonio Spurs",
    defeated: "Cleveland Cavaliers",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: Spurs 83, Cavaliers 82",
  },
  2008: {
    team: "Boston Celtics",
    defeated: "Los Angeles Lakers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Celtics 131, Lakers 92",
  },
  2009: {
    team: "Los Angeles Lakers",
    defeated: "Orlando Magic",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Lakers 99, Magic 86",
  },
  2010: {
    team: "Los Angeles Lakers",
    defeated: "Boston Celtics",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Lakers 83, Celtics 79",
  },
  2011: {
    team: "Dallas Mavericks",
    defeated: "Miami Heat",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Mavericks 105, Heat 95",
  },
  2012: {
    team: "Miami Heat",
    defeated: "Oklahoma City Thunder",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Heat 121, Thunder 106",
  },
  2013: {
    team: "Miami Heat",
    defeated: "San Antonio Spurs",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Heat 95, Spurs 88",
  },
  2014: {
    team: "San Antonio Spurs",
    defeated: "Miami Heat",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Spurs 104, Heat 87",
  },
  2015: {
    team: "Golden State Warriors",
    defeated: "Cleveland Cavaliers",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Warriors 105, Cavaliers 97",
  },
  2016: {
    team: "Cleveland Cavaliers",
    defeated: "Golden State Warriors",
    seriesResult: "4-3",
    lastGameResult: "Juego 7: Cavaliers 93, Warriors 89",
  },
  2017: {
    team: "Golden State Warriors",
    defeated: "Cleveland Cavaliers",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Warriors 129, Cavaliers 120",
  },
  2018: {
    team: "Golden State Warriors",
    defeated: "Cleveland Cavaliers",
    seriesResult: "4-0",
    lastGameResult: "Juego 4: Warriors 108, Cavaliers 85",
  },
  2019: {
    team: "Toronto Raptors",
    defeated: "Golden State Warriors",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Raptors 114, Warriors 110",
  },
  2020: {
    team: "Los Angeles Lakers",
    defeated: "Miami Heat",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Lakers 106, Heat 93",
  },
  2021: {
    team: "Milwaukee Bucks",
    defeated: "Phoenix Suns",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Bucks 105, Suns 98",
  },
  2022: {
    team: "Golden State Warriors",
    defeated: "Boston Celtics",
    seriesResult: "4-2",
    lastGameResult: "Juego 6: Warriors 103, Celtics 90",
  },
  2023: {
    team: "Denver Nuggets",
    defeated: "Miami Heat",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Nuggets 94, Heat 89",
  },
  2024: {
    team: "Boston Celtics",
    defeated: "Dallas Mavericks",
    seriesResult: "4-1",
    lastGameResult: "Juego 5: Celtics 106, Mavericks 88",
  },
};
